//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotaSHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int review_id { get; set; }
        public int transaction_id { get; set; }
        public int reviewer_id { get; set; }
        public int rating { get; set; }
        public System.DateTime review_date { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual transactions transactions { get; set; }
        public virtual users users { get; set; }
    }
}
